### ISSUE TITLE
Compile Issue 

### ISSUE THREAD

**Issue by andrewpsp** [BitcoinInterestOfficial/BitcoinInterest#7]
Consistent Error after all dependencies were install

``` 

ubuntu@ip-172-31-50-47:~/source/BitcoinInterest$ sudo make && sudo make install
Making all in src

make[1]: Entering directory '/home/ubuntu/source/BitcoinInterest/src'
make[2]: Entering directory '/home/ubuntu/source/BitcoinInterest/src'
make[3]: Entering directory '/home/ubuntu/source/BitcoinInterest'
make[3]: Leaving directory '/home/ubuntu/source/BitcoinInterest'
make[3]: Entering directory '/home/ubuntu/source/BitcoinInterest/src/univalue'
make[3]: *** No rule to make target 'libunivalue.la'.  Stop.
make[3]: Leaving directory '/home/ubuntu/source/BitcoinInterest/src/univalue'
Makefile:9853: recipe for target 'univalue/libunivalue.la' failed
make[2]: *** [univalue/libunivalue.la] Error 2
make[2]: Leaving directory '/home/ubuntu/source/BitcoinInterest/src'
Makefile:9349: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/source/BitcoinInterest/src'
Makefile:742: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

**Comment by mathis1337** [comment]
This happens when you have incorrectly installed boost or have an incompatible version. 

First try make clean. 

If that doesn't try removing boost and installing the recommended version.
 
sudo apt-get autoremove libboost-all-dev
sudo apt-get install libboost-all-dev

**Comment by andrewpsp** [comment]
I'm actually still getting the exact same issue.

**Comment by mathis1337** [comment]
Then boost was not uninstall properly or you still have wrong version. Boost can be a pain and the whole libsodium library. Don't use the one in the dependency folder. We've had many others successfully build this so I am confident your error is definitely a  library issue.

**Comment by andrewpsp** [comment]
Currently walking down this issue. 

``` ubuntu@ip-172-31-50-47:~$ dpkg -s libboost-dev | grep 'Version'
Version: 1.58.0.1ubuntu1 ```     I shall update to 1.62x to find if this solve the current issue.

**Comment by mathis1337** [comment]
Workaround for Ubuntu 16.04 Xenial Users

Download deb files from https://packages.ubuntu.com/artful/libsodium-dev and https://packages.ubuntu.com/artful/libsodium18 for your architecture, e.g.

wget http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium-dev_1.0.13-1_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.13-1_amd64.deb

This gives you libsodium 1.0.13 from Ubuntu 17.10 (Artful) which can be installed on 16.04 without problems since it only has a dependency on libc6:

dpkg -i libsodium*deb
Now compile BCI. No assertion anymore when starting bcid.

or, if that doesnt work:

Solution

Step 1) Install Dependencies:

sudo apt install libsodium18

Manually compile / install libsodium-dev v1.0.13 or later from https://download.libsodium.org/libsodium/releases/ (Make sure no older versions are installed)

./configure && make && make test && sudo make install

./sudo ldconfig
